Use UID instead of username for virt-api and virt-controller pods
The fix is mentioned in the openshift guidelines:

  https://docs.openshift.org/latest/creating_images/guidelines.html

Without this the pods fail to start with the following error:

  Error: container has runAsNonRoot and image has non-numeric user (virt-api),
  cannot verify user is non-root

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>